<dec f='luajit/host/buildvm.h' l='68' type='struct dasm_State *'/>
<use f='luajit/dasm_x86.h' l='89' macro='1' u='w' c='dasm_init'/>
<use f='luajit/dasm_x86.h' l='90' macro='1' u='w' c='dasm_init'/>
<use f='luajit/dasm_x86.h' l='90' macro='1' u='r' c='dasm_init'/>
<use f='luajit/dasm_x86.h' l='90' macro='1' u='r' c='dasm_init'/>
<use f='luajit/dasm_x86.h' l='91' macro='1' u='r' c='dasm_init'/>
<use f='luajit/dasm_x86.h' l='110' macro='1' u='r' c='dasm_free'/>
<use f='luajit/dasm_x86.h' l='123' macro='1' u='r' c='dasm_setupglobal'/>
<use f='luajit/dasm_x86.h' l='131' macro='1' u='r' c='dasm_growpc'/>
<use f='luajit/dasm_x86.h' l='140' macro='1' u='r' c='dasm_setup'/>
<use f='luajit/dasm_x86.h' l='170' macro='1' u='r' c='dasm_put'/>
<use f='luajit/dasm_x86.h' l='279' macro='1' u='r' c='dasm_link'/>
<use f='luajit/dasm_x86.h' l='391' macro='1' u='r' c='dasm_encode'/>
<use f='luajit/dasm_x86.h' l='501' macro='1' u='r' c='dasm_getpclabel'/>
<use f='luajit/dasm_x86.h' l='514' macro='1' u='r' c='dasm_checkstep'/>
<offset>0</offset>
<doc f='luajit/host/buildvm.h' l='67'>/* DynASM state pointer. Should be first member. */</doc>
