<dec f='luajit/lj_ir.h' l='556' type='uint8_t'/>
<offset>48</offset>
<doc f='luajit/lj_ir.h' l='556'>/* Register allocation (overlaps prev). */</doc>
<use f='luajit/lj_asm.c' l='343' u='r' c='ra_rematk'/>
<use f='luajit/lj_asm.c' l='349' u='w' c='ra_rematk'/>
<use f='luajit/lj_asm.c' l='357' u='w' c='ra_rematk'/>
<use f='luajit/lj_asm.c' l='411' u='r' c='ra_releasetmp'/>
<use f='luajit/lj_asm.c' l='417' u='w' c='ra_releasetmp'/>
<use f='luajit/lj_asm.c' l='429' u='r' c='ra_restore'/>
<use f='luajit/lj_asm.c' l='431' u='w' c='ra_restore'/>
<use f='luajit/lj_asm.c' l='471' u='r' c='ra_evict'/>
<use f='luajit/lj_asm.c' l='629' u='r' c='ra_allocref'/>
<use f='luajit/lj_asm.c' l='630' u='r' c='ra_allocref'/>
<use f='luajit/lj_asm.c' l='656' u='w' c='ra_allocref'/>
<use f='luajit/lj_asm.c' l='666' u='r' c='ra_alloc1'/>
<use f='luajit/lj_asm.c' l='679' u='w' c='ra_addrename'/>
<use f='luajit/lj_asm.c' l='688' u='w' c='ra_rename'/>
<use f='luajit/lj_asm.c' l='718' u='r' c='ra_dest'/>
<use f='luajit/lj_asm.c' l='730' u='w' c='ra_dest'/>
<use f='luajit/lj_asm.c' l='754' u='r' c='ra_left'/>
<use f='luajit/lj_asm.c' l='782' u='w' c='ra_left'/>
<use f='luajit/lj_asm.c' l='906' u='r' c='asm_snap_alloc1'/>
<use f='luajit/lj_asm.c' l='309' u='r' c='asm_snap_alloc1'/>
<use f='luajit/lj_asm.c' l='910' u='r' c='asm_snap_alloc1'/>
<use f='luajit/lj_asm.c' l='911' u='w' c='asm_snap_alloc1'/>
<use f='luajit/lj_asm.c' l='924' u='r' c='asm_snap_alloc1'/>
<use f='luajit/lj_asm.c' l='940' u='r' c='asm_snap_alloc1'/>
<use f='luajit/lj_asm.c' l='940' u='r' c='asm_snap_alloc1'/>
<use f='luajit/lj_asm.c' l='309' u='r' c='asm_gcstep'/>
<use f='luajit/lj_asm.c' l='1155' u='r' c='asm_bufhdr'/>
<use f='luajit/lj_asm.c' l='309' u='r' c='asm_bufhdr'/>
<use f='luajit/lj_asm.c' l='1196' u='r' c='asm_bufput'/>
<use f='luajit/lj_asm.c' l='1298' u='r' c='asm_newref'/>
<use f='luajit/lj_asm.c' l='1428' u='r' c='asm_phi_shuffle'/>
<use f='luajit/lj_asm.c' l='1579' u='r' c='asm_phi'/>
<use f='luajit/lj_asm.c' l='1587' u='r' c='asm_phi'/>
<use f='luajit/lj_asm.c' l='1591' u='r' c='asm_phi'/>
<use f='luajit/lj_asm.c' l='1593' u='w' c='asm_phi'/>
<use f='luajit/lj_asm.c' l='1597' u='r' c='asm_phi'/>
<use f='luajit/lj_asm.c' l='1598' u='w' c='asm_phi'/>
<use f='luajit/lj_asm.c' l='1601' u='r' c='asm_phi'/>
<use f='luajit/lj_asm.c' l='1601' u='r' c='asm_phi'/>
<use f='luajit/lj_asm_x86.h' l='166' u='r' c='asm_fusearef'/>
<use f='luajit/lj_asm_x86.h' l='184' u='r' c='asm_fuseahuref'/>
<use f='luajit/lj_asm_x86.h' l='328' u='r' c='asm_fusexref'/>
<use f='luajit/lj_asm_x86.h' l='336' u='r' c='asm_fusexref'/>
<use f='luajit/lj_asm_x86.h' l='348' u='r' c='asm_fusexref'/>
<use f='luajit/lj_asm_x86.h' l='412' u='r' c='asm_fuseload'/>
<use f='luajit/lj_asm_x86.h' l='414' u='r' c='asm_fuseload'/>
<use f='luajit/lj_asm_x86.h' l='415' u='r' c='asm_fuseload'/>
<use f='luajit/lj_asm_x86.h' l='614' u='r' c='asm_gencall'/>
<use f='luajit/lj_asm_x86.h' l='615' u='r' c='asm_gencall'/>
<use f='luajit/lj_asm_x86.h' l='616' u='r' c='asm_gencall'/>
<use f='luajit/lj_asm_x86.h' l='657' u='r' c='asm_setupresult'/>
<use f='luajit/lj_asm_x86.h' l='658' u='r' c='asm_setupresult'/>
<use f='luajit/lj_asm_x86.h' l='659' u='r' c='asm_setupresult'/>
<use f='luajit/lj_asm_x86.h' l='660' u='r' c='asm_setupresult'/>
<use f='luajit/lj_asm_x86.h' l='662' macro='1' u='r' c='asm_setupresult'/>
<use f='luajit/lj_asm_x86.h' l='667' u='r' c='asm_setupresult'/>
<use f='luajit/lj_asm_x86.h' l='802' u='r' c='asm_tobit'/>
<use f='luajit/lj_asm_x86.h' l='866' u='r' c='asm_conv'/>
<use f='luajit/lj_asm_x86.h' l='1037' u='r' c='asm_strto'/>
<use f='luajit/lj_asm_x86.h' l='1038' u='r' c='asm_strto'/>
<use f='luajit/lj_asm_x86.h' l='1117' macro='1' u='r' c='asm_href'/>
<use f='luajit/lj_asm_x86.h' l='1277' macro='1' u='r' c='asm_hrefk'/>
<use f='luajit/lj_asm_x86.h' l='1430' u='r' c='asm_fxstore'/>
<use f='luajit/lj_asm_x86.h' l='1532' macro='1' u='r' c='asm_ahuvload'/>
<use f='luajit/lj_asm_x86.h' l='1600' u='r' c='asm_ahustore'/>
<use f='luajit/lj_asm_x86.h' l='1695' macro='1' u='r' c='asm_sload'/>
<use f='luajit/lj_asm_x86.h' l='1901' u='r' c='asm_obar'/>
<use f='luajit/lj_asm_x86.h' l='1931' macro='1' u='r' c='asm_x87load'/>
<use f='luajit/lj_asm_x86.h' l='1965' u='r' c='asm_fpmath'/>
<use f='luajit/lj_asm_x86.h' l='1966' u='r' c='asm_fpmath'/>
<use f='luajit/lj_asm_x86.h' l='1981' u='r' c='asm_ldexp'/>
<use f='luajit/lj_asm_x86.h' l='1998' u='r' c='asm_fppowi'/>
<use f='luajit/lj_asm_x86.h' l='1999' u='r' c='asm_fppowi'/>
<use f='luajit/lj_asm_x86.h' l='2016' u='r' c='asm_swapops'/>
<use f='luajit/lj_asm_x86.h' l='2018' u='r' c='asm_swapops'/>
<use f='luajit/lj_asm_x86.h' l='2018' u='r' c='asm_swapops'/>
<use f='luajit/lj_asm_x86.h' l='2037' u='r' c='asm_fparith'/>
<use f='luajit/lj_asm_x86.h' l='2071' u='r' c='asm_intarith'/>
<use f='luajit/lj_asm_x86.h' l='2131' u='r' c='asm_lea'/>
<use f='luajit/lj_asm_x86.h' l='2132' u='r' c='asm_lea'/>
<use f='luajit/lj_asm_x86.h' l='2133' u='r' c='asm_lea'/>
<use f='luajit/lj_asm_x86.h' l='2134' u='r' c='asm_lea'/>
<use f='luajit/lj_asm_x86.h' l='2135' u='r' c='asm_lea'/>
<use f='luajit/lj_asm_x86.h' l='2137' u='r' c='asm_lea'/>
<use f='luajit/lj_asm_x86.h' l='2138' u='r' c='asm_lea'/>
<use f='luajit/lj_asm_x86.h' l='2139' u='r' c='asm_lea'/>
<use f='luajit/lj_asm_x86.h' l='2144' u='r' c='asm_lea'/>
<use f='luajit/lj_asm_x86.h' l='2145' u='r' c='asm_lea'/>
<use f='luajit/lj_asm_x86.h' l='2146' u='r' c='asm_lea'/>
<use f='luajit/lj_asm_x86.h' l='2305' u='r' c='asm_bitshift'/>
<use f='luajit/lj_asm_x86.h' l='2414' macro='1' u='r' c='asm_comp'/>
<use f='luajit/lj_asm_x86.h' l='2666' u='r' c='asm_stack_check'/>
<use f='luajit/lj_asm_x86.h' l='2846' u='r' c='asm_head_root_base'/>
<use f='luajit/lj_asm_x86.h' l='2850' u='w' c='asm_head_root_base'/>
<use f='luajit/lj_asm_x86.h' l='2860' u='r' c='asm_head_side_base'/>
<use f='luajit/lj_asm_x86.h' l='2864' u='w' c='asm_head_side_base'/>
<use f='luajit/lj_asm_x86.h' l='2865' u='r' c='asm_head_side_base'/>
<use f='luajit/lj_asm_x86.h' l='2867' u='r' c='asm_head_side_base'/>
<use f='luajit/lj_asm_x86.h' l='2867' u='r' c='asm_head_side_base'/>
<use f='luajit/lj_asm_x86.h' l='2869' u='r' c='asm_head_side_base'/>
<use f='luajit/lj_asm_x86.h' l='2870' u='r' c='asm_head_side_base'/>
<use f='luajit/lj_asm.c' l='1895' u='r' c='asm_head_side'/>
<use f='luajit/lj_asm.c' l='1896' u='r' c='asm_head_side'/>
<use f='luajit/lj_asm.c' l='1898' u='r' c='asm_head_side'/>
<use f='luajit/lj_asm.c' l='1905' u='r' c='asm_head_side'/>
<use f='luajit/lj_asm.c' l='1906' u='r' c='asm_head_side'/>
<use f='luajit/lj_asm.c' l='1908' u='r' c='asm_head_side'/>
<use f='luajit/lj_asm.c' l='309' u='r' c='asm_head_side'/>
<use f='luajit/lj_asm.c' l='1936' u='w' c='asm_head_side'/>
<use f='luajit/lj_asm.c' l='1993' u='r' c='asm_head_side'/>
<use f='luajit/lj_asm.c' l='1994' u='r' c='asm_head_side'/>
<use f='luajit/lj_asm.c' l='2174' u='r' c='asm_setup_regsp'/>
<use f='luajit/lj_asm.c' l='2176' u='r' c='asm_setup_regsp'/>
<use f='luajit/lj_asm.c' l='2177' u='w' c='asm_setup_regsp'/>
<use f='luajit/lj_asm.c' l='2331' u='r' c='asm_setup_regsp'/>
<use f='luajit/lj_asm.c' l='2332' u='w' c='asm_setup_regsp'/>
<use f='luajit/lj_asm.c' l='309' u='r' c='lj_asm_trace'/>
<use f='luajit/lj_snap.c' l='523' u='r' c='lj_snap_replay'/>
<use f='luajit/lj_snap.c' l='537' u='r' c='lj_snap_replay'/>
<use f='luajit/lj_snap.c' l='556' u='r' c='lj_snap_replay'/>
<use f='luajit/lj_snap.c' l='578' u='r' c='lj_snap_replay'/>
<use f='luajit/lj_snap.c' l='802' u='r' c='snap_unsink'/>
<use f='luajit/lj_snap.c' l='840' u='r' c='snap_unsink'/>
<use f='luajit/lj_snap.c' l='908' u='r' c='lj_snap_restore'/>
