<dec f='luajit/lj_ir.h' l='552' type='IRType1'/>
<use f='luajit/lj_ir.h' l='586' u='m' c='ir_sideeff'/>
<offset>32</offset>
<doc f='luajit/lj_ir.h' l='552'>/* IR type. */</doc>
<use f='luajit/lib_jit.c' l='352' u='m' c='lj_cf_jit_util_tracek'/>
<use f='luajit/lj_emit_x86.h' l='525' u='m' c='emit_movrr'/>
<use f='luajit/lj_emit_x86.h' l='525' u='m' c='emit_loadofs'/>
<use f='luajit/lj_emit_x86.h' l='548' u='m' c='emit_loadofs'/>
<use f='luajit/lj_emit_x86.h' l='525' u='m' c='emit_storeofs'/>
<use f='luajit/lj_emit_x86.h' l='557' u='m' c='emit_storeofs'/>
<use f='luajit/lj_asm.c' l='389' u='m' c='ra_spill'/>
<use f='luajit/lj_asm.c' l='641' u='m' c='ra_allocref'/>
<use f='luajit/lj_asm.c' l='659' u='m' c='ra_allocref'/>
<use f='luajit/lj_asm.c' l='789' u='m' c='ra_left'/>
<use f='luajit/lj_asm.c' l='946' u='m' c='asm_snap_alloc1'/>
<use f='luajit/lj_asm.c' l='946' u='m' c='asm_snap_alloc1'/>
<use f='luajit/lj_asm.c' l='951' u='m' c='asm_snap_alloc1'/>
<use f='luajit/lj_asm.c' l='1066' u='m' c='ir_khash'/>
<use f='luajit/lj_asm.c' l='1068' u='m' c='ir_khash'/>
<use f='luajit/lj_asm.c' l='1071' u='m' c='ir_khash'/>
<use f='luajit/lj_asm.c' l='1073' u='m' c='ir_khash'/>
<use f='luajit/lj_asm.c' l='1078' u='m' c='ir_khash'/>
<use f='luajit/lj_asm.c' l='1357' u='m' c='asm_callx_flags'/>
<use f='luajit/lj_asm.c' l='1433' u='m' c='asm_phi_shuffle'/>
<use f='luajit/lj_asm.c' l='1483' u='m' c='asm_phi_shuffle'/>
<use f='luajit/lj_asm.c' l='1499' u='m' c='asm_phi_copyspill'/>
<use f='luajit/lj_asm.c' l='1499' u='m' c='asm_phi_copyspill'/>
<use f='luajit/lj_asm.c' l='1513' u='m' c='asm_phi_copyspill'/>
<use f='luajit/lj_asm.c' l='1513' u='m' c='asm_phi_copyspill'/>
<use f='luajit/lj_asm.c' l='1539' u='m' c='asm_phi_copyspill'/>
<use f='luajit/lj_asm.c' l='1539' u='m' c='asm_phi_copyspill'/>
<use f='luajit/lj_asm.c' l='1560' u='m' c='asm_phi_fixup'/>
<use f='luajit/lj_asm.c' l='1561' u='m' c='asm_phi_fixup'/>
<use f='luajit/lj_asm.c' l='1574' u='m' c='asm_phi'/>
<use f='luajit/lj_asm.c' l='1574' u='m' c='asm_phi'/>
<use f='luajit/lj_asm.c' l='1596' u='m' c='asm_phi'/>
<use f='luajit/lj_asm_x86.h' l='89' u='m' c='asm_isk32'/>
<use f='luajit/lj_asm_x86.h' l='328' macro='1' u='m' c='asm_fusexref'/>
<use f='luajit/lj_asm_x86.h' l='336' macro='1' u='m' c='asm_fusexref'/>
<use f='luajit/lj_asm_x86.h' l='348' macro='1' u='m' c='asm_fusexref'/>
<use f='luajit/lj_asm_x86.h' l='452' u='m' c='asm_fuseload'/>
<use f='luajit/lj_asm_x86.h' l='461' u='m' c='asm_fuseload'/>
<use f='luajit/lj_asm_x86.h' l='461' u='m' c='asm_fuseload'/>
<use f='luajit/lj_asm_x86.h' l='461' u='m' c='asm_fuseload'/>
<use f='luajit/lj_asm_x86.h' l='468' u='m' c='asm_fuseload'/>
<use f='luajit/lj_asm_x86.h' l='476' u='m' c='asm_fuseload'/>
<use f='luajit/lj_asm_x86.h' l='481' u='m' c='asm_fuseload'/>
<use f='luajit/lj_asm_x86.h' l='500' u='m' c='asm_fuseloadm'/>
<use f='luajit/lj_asm_x86.h' l='521' u='m' c='asm_count_call_slots'/>
<use f='luajit/lj_asm_x86.h' l='521' u='m' c='asm_count_call_slots'/>
<use f='luajit/lj_asm_x86.h' l='590' u='m' c='asm_gencall'/>
<use f='luajit/lj_asm_x86.h' l='590' u='m' c='asm_gencall'/>
<use f='luajit/lj_asm_x86.h' l='621' u='m' c='asm_gencall'/>
<use f='luajit/lj_asm_x86.h' l='621' u='m' c='asm_gencall'/>
<use f='luajit/lj_asm_x86.h' l='630' u='m' c='asm_gencall'/>
<use f='luajit/lj_asm_x86.h' l='633' u='m' c='asm_gencall'/>
<use f='luajit/lj_asm_x86.h' l='654' u='m' c='asm_setupresult'/>
<use f='luajit/lj_asm_x86.h' l='663' u='m' c='asm_setupresult'/>
<use f='luajit/lj_asm_x86.h' l='663' u='m' c='asm_setupresult'/>
<use f='luajit/lj_asm_x86.h' l='702' u='m' c='asm_setupresult'/>
<use f='luajit/lj_asm_x86.h' l='702' u='m' c='asm_setupresult'/>
<use f='luajit/lj_asm_x86.h' l='772' u='m' c='asm_retf'/>
<use f='luajit/lj_asm_x86.h' l='822' u='m' c='asm_conv'/>
<use f='luajit/lj_asm_x86.h' l='822' u='m' c='asm_conv'/>
<use f='luajit/lj_asm_x86.h' l='832' u='m' c='asm_conv'/>
<use f='luajit/lj_asm_x86.h' l='850' u='m' c='asm_conv'/>
<use f='luajit/lj_asm_x86.h' l='855' u='m' c='asm_conv'/>
<use f='luajit/lj_asm_x86.h' l='863' u='m' c='asm_conv'/>
<use f='luajit/lj_asm_x86.h' l='863' u='m' c='asm_conv'/>
<use f='luajit/lj_asm_x86.h' l='881' u='m' c='asm_conv'/>
<use f='luajit/lj_asm_x86.h' l='885' u='m' c='asm_conv'/>
<use f='luajit/lj_asm_x86.h' l='885' u='m' c='asm_conv'/>
<use f='luajit/lj_asm_x86.h' l='916' u='m' c='asm_conv'/>
<use f='luajit/lj_asm_x86.h' l='1056' u='m' c='asm_tvptr'/>
<use f='luajit/lj_asm_x86.h' l='1073' u='m' c='asm_tvptr'/>
<use f='luajit/lj_asm_x86.h' l='1074' u='m' c='asm_tvptr'/>
<use f='luajit/lj_asm_x86.h' l='1078' u='m' c='asm_tvptr'/>
<use f='luajit/lj_asm_x86.h' l='1080' macro='1' u='m' c='asm_tvptr'/>
<use f='luajit/lj_asm_x86.h' l='1123' u='r' c='asm_href'/>
<use f='luajit/lj_asm_x86.h' l='1181' u='m' c='asm_href'/>
<use f='luajit/lj_asm_x86.h' l='1295' u='m' c='asm_hrefk'/>
<use f='luajit/lj_asm_x86.h' l='1302' u='m' c='asm_hrefk'/>
<use f='luajit/lj_asm_x86.h' l='1304' u='m' c='asm_hrefk'/>
<use f='luajit/lj_asm_x86.h' l='1313' u='m' c='asm_hrefk'/>
<use f='luajit/lj_asm_x86.h' l='1396' u='m' c='asm_fxload'/>
<use f='luajit/lj_asm_x86.h' l='1396' u='m' c='asm_fxload'/>
<use f='luajit/lj_asm_x86.h' l='1403' u='m' c='asm_fxload'/>
<use f='luajit/lj_asm_x86.h' l='1411' u='m' c='asm_fxload'/>
<use f='luajit/lj_asm_x86.h' l='1435' u='m' c='asm_fxstore'/>
<use f='luajit/lj_asm_x86.h' l='1435' u='m' c='asm_fxstore'/>
<use f='luajit/lj_asm_x86.h' l='1435' u='m' c='asm_fxstore'/>
<use f='luajit/lj_asm_x86.h' l='1435' u='m' c='asm_fxstore'/>
<use f='luajit/lj_asm_x86.h' l='1437' u='m' c='asm_fxstore'/>
<use f='luajit/lj_asm_x86.h' l='1437' u='m' c='asm_fxstore'/>
<use f='luajit/lj_asm_x86.h' l='1438' u='m' c='asm_fxstore'/>
<use f='luajit/lj_asm_x86.h' l='1438' u='m' c='asm_fxstore'/>
<use f='luajit/lj_asm_x86.h' l='1454' u='m' c='asm_fxstore'/>
<use f='luajit/lj_asm_x86.h' l='1465' u='m' c='asm_fxstore'/>
<use f='luajit/lj_asm_x86.h' l='1479' u='m' c='asm_fxstore'/>
<use f='luajit/lj_asm_x86.h' l='1479' u='m' c='asm_fxstore'/>
<use f='luajit/lj_asm_x86.h' l='1486' macro='1' u='m' c='asm_fxstore'/>
<use f='luajit/lj_asm_x86.h' l='1533' u='m' c='asm_ahuvload'/>
<use f='luajit/lj_asm_x86.h' l='1537' u='m' c='asm_ahuvload'/>
<use f='luajit/lj_asm_x86.h' l='1540' u='m' c='asm_ahuvload'/>
<use f='luajit/lj_asm_x86.h' l='1557' u='m' c='asm_ahuvload'/>
<use f='luajit/lj_asm_x86.h' l='1566' u='m' c='asm_ahuvload'/>
<use f='luajit/lj_asm_x86.h' l='1567' u='m' c='asm_ahuvload'/>
<use f='luajit/lj_asm_x86.h' l='1577' u='m' c='asm_ahuvload'/>
<use f='luajit/lj_asm_x86.h' l='1579' u='m' c='asm_ahuvload'/>
<use f='luajit/lj_asm_x86.h' l='1583' u='m' c='asm_ahuvload'/>
<use f='luajit/lj_asm_x86.h' l='1588' u='m' c='asm_ahuvload'/>
<use f='luajit/lj_asm_x86.h' l='1602' u='m' c='asm_ahustore'/>
<use f='luajit/lj_asm_x86.h' l='1639' u='m' c='asm_ahustore'/>
<use f='luajit/lj_asm_x86.h' l='1642' u='m' c='asm_ahustore'/>
<use f='luajit/lj_asm_x86.h' l='1650' u='m' c='asm_ahustore'/>
<use f='luajit/lj_asm_x86.h' l='1671' u='r' c='asm_sload'/>
<use f='luajit/lj_asm_x86.h' l='2021' u='m' c='asm_swapops'/>
<use f='luajit/lj_asm_x86.h' l='2023' u='m' c='asm_swapops'/>
<use f='luajit/lj_asm_x86.h' l='2083' u='m' c='asm_intarith'/>
<use f='luajit/lj_asm_x86.h' l='2085' u='m' c='asm_intarith'/>
<use f='luajit/lj_asm_x86.h' l='2089' macro='1' u='m' c='asm_intarith'/>
<use f='luajit/lj_asm_x86.h' l='2091' macro='1' u='m' c='asm_intarith'/>
<use f='luajit/lj_asm_x86.h' l='2093' macro='1' u='m' c='asm_intarith'/>
<use f='luajit/lj_asm_x86.h' l='2096' u='m' c='asm_intarith'/>
<use f='luajit/lj_asm_x86.h' l='2100' macro='1' u='m' c='asm_intarith'/>
<use f='luajit/lj_asm_x86.h' l='2138' u='m' c='asm_lea'/>
<use f='luajit/lj_asm_x86.h' l='2139' u='m' c='asm_lea'/>
<use f='luajit/lj_asm_x86.h' l='2181' u='m' c='asm_add'/>
<use f='luajit/lj_asm_x86.h' l='2183' u='m' c='asm_add'/>
<use f='luajit/lj_asm_x86.h' l='2189' u='m' c='asm_sub'/>
<use f='luajit/lj_asm_x86.h' l='2197' u='m' c='asm_mul'/>
<use f='luajit/lj_asm_x86.h' l='2208' macro='1' u='m' c='asm_neg_not'/>
<use f='luajit/lj_asm_x86.h' l='2214' u='m' c='asm_neg'/>
<use f='luajit/lj_asm_x86.h' l='2228' macro='1' u='m' c='asm_intmin_max'/>
<use f='luajit/lj_asm_x86.h' l='2229' macro='1' u='m' c='asm_intmin_max'/>
<use f='luajit/lj_asm_x86.h' l='2235' u='m' c='asm_min'/>
<use f='luajit/lj_asm_x86.h' l='2243' u='m' c='asm_max'/>
<use f='luajit/lj_asm_x86.h' l='2260' macro='1' u='m' c='asm_bswap'/>
<use f='luajit/lj_asm_x86.h' l='2276' u='m' c='asm_bitshift'/>
<use f='luajit/lj_asm_x86.h' l='2278' u='m' c='asm_bitshift'/>
<use f='luajit/lj_asm_x86.h' l='2281' macro='1' u='m' c='asm_bitshift'/>
<use f='luajit/lj_asm_x86.h' l='2287' macro='1' u='m' c='asm_bitshift'/>
<use f='luajit/lj_asm_x86.h' l='2288' macro='1' u='m' c='asm_bitshift'/>
<use f='luajit/lj_asm_x86.h' l='2295' u='m' c='asm_bitshift'/>
<use f='luajit/lj_asm_x86.h' l='2296' macro='1' u='m' c='asm_bitshift'/>
<use f='luajit/lj_asm_x86.h' l='2303' macro='1' u='m' c='asm_bitshift'/>
<use f='luajit/lj_asm_x86.h' l='2310' macro='1' u='m' c='asm_bitshift'/>
<use f='luajit/lj_asm_x86.h' l='2358' u='m' c='asm_comp'/>
<use f='luajit/lj_asm_x86.h' l='2399' macro='1' u='m' c='asm_comp'/>
<use f='luajit/lj_asm_x86.h' l='2424' u='m' c='asm_comp'/>
<use f='luajit/lj_asm_x86.h' l='2424' u='m' c='asm_comp'/>
<use f='luajit/lj_asm_x86.h' l='2425' u='r' c='asm_comp'/>
<use f='luajit/lj_asm_x86.h' l='2426' u='m' c='asm_comp'/>
<use f='luajit/lj_asm_x86.h' l='2426' u='m' c='asm_comp'/>
<use f='luajit/lj_asm_x86.h' l='2430' u='w' c='asm_comp'/>
<use f='luajit/lj_asm_x86.h' l='2453' u='m' c='asm_comp'/>
<use f='luajit/lj_asm_x86.h' l='2454' u='m' c='asm_comp'/>
<use f='luajit/lj_asm_x86.h' l='2454' u='m' c='asm_comp'/>
<use f='luajit/lj_asm_x86.h' l='2455' u='m' c='asm_comp'/>
<use f='luajit/lj_asm_x86.h' l='2463' u='r' c='asm_comp'/>
<use f='luajit/lj_asm_x86.h' l='2464' u='m' c='asm_comp'/>
<use f='luajit/lj_asm_x86.h' l='2464' u='m' c='asm_comp'/>
<use f='luajit/lj_asm_x86.h' l='2466' u='w' c='asm_comp'/>
<use f='luajit/lj_asm_x86.h' l='2468' u='m' c='asm_comp'/>
<use f='luajit/lj_asm_x86.h' l='2468' u='m' c='asm_comp'/>
<use f='luajit/lj_asm_x86.h' l='2478' u='m' c='asm_comp'/>
<use f='luajit/lj_asm_x86.h' l='2484' u='m' c='asm_comp'/>
<use f='luajit/lj_asm_x86.h' l='2707' u='m' c='asm_stack_restore'/>
<use f='luajit/lj_asm_x86.h' l='2717' u='m' c='asm_stack_restore'/>
<use f='luajit/lj_asm_x86.h' l='2719' u='m' c='asm_stack_restore'/>
<use f='luajit/lj_asm_x86.h' l='2721' u='m' c='asm_stack_restore'/>
<use f='luajit/lj_asm_x86.h' l='2724' u='m' c='asm_stack_restore'/>
<use f='luajit/lj_asm_x86.h' l='2727' macro='1' u='m' c='asm_stack_restore'/>
<use f='luajit/lj_asm_x86.h' l='2849' u='m' c='asm_head_root_base'/>
<use f='luajit/lj_asm_x86.h' l='2863' u='m' c='asm_head_side_base'/>
<use f='luajit/lj_asm_x86.h' l='2952' u='m' c='asm_setup_call_slots'/>
<use f='luajit/lj_asm_x86.h' l='2952' u='m' c='asm_setup_call_slots'/>
<use f='luajit/lj_asm.c' l='1660' u='m' c='asm_pow'/>
<use f='luajit/lj_asm.c' l='1661' u='m' c='asm_pow'/>
<use f='luajit/lj_asm.c' l='1665' u='m' c='asm_pow'/>
<use f='luajit/lj_asm.c' l='1674' u='m' c='asm_div'/>
<use f='luajit/lj_asm.c' l='1675' u='m' c='asm_div'/>
<use f='luajit/lj_asm.c' l='1686' u='m' c='asm_mod'/>
<use f='luajit/lj_asm.c' l='1687' u='m' c='asm_mod'/>
<use f='luajit/lj_asm.c' l='1724' u='m' c='asm_ir'/>
<use f='luajit/lj_asm.c' l='1724' u='m' c='asm_ir'/>
<use f='luajit/lj_asm.c' l='1902' u='m' c='asm_head_side'/>
<use f='luajit/lj_asm.c' l='1929' u='m' c='asm_head_side'/>
<use f='luajit/lj_asm.c' l='1933' u='m' c='asm_head_side'/>
<use f='luajit/lj_asm.c' l='1939' u='m' c='asm_head_side'/>
<use f='luajit/lj_asm.c' l='1939' u='m' c='asm_head_side'/>
<use f='luajit/lj_asm.c' l='2128' u='m' c='asm_setup_regsp'/>
<use f='luajit/lj_asm.c' l='2281' u='m' c='asm_setup_regsp'/>
<use f='luajit/lj_asm.c' l='2297' u='m' c='asm_setup_regsp'/>
<use f='luajit/lj_asm.c' l='2346' u='m' c='asm_setup_regsp'/>
<use f='luajit/lj_asm.c' l='2346' u='m' c='asm_setup_regsp'/>
<use f='luajit/lj_asm.c' l='2466' u='m' c='lj_asm_trace'/>
<use f='luajit/lj_gc.c' l='261' u='m' c='gc_traverse_trace'/>
<use f='luajit/lj_ir.c' l='126' u='m' c='lj_ir_emit'/>
<use f='luajit/lj_ir.c' l='127' u='w' c='lj_ir_emit'/>
<use f='luajit/lj_ir.c' l='127' u='r' c='lj_ir_emit'/>
<use f='luajit/lj_ir.c' l='209' u='m' c='lj_ir_kint'/>
<use f='luajit/lj_ir.c' l='229' u='m' c='lj_ir_k64'/>
<use f='luajit/lj_ir.c' l='291' u='m' c='lj_ir_kgc'/>
<use f='luajit/lj_ir.c' l='305' u='m' c='lj_ir_ktrace'/>
<use f='luajit/lj_ir.c' l='331' u='m' c='lj_ir_kptr_'/>
<use f='luajit/lj_ir.c' l='345' u='m' c='lj_ir_knull'/>
<use f='luajit/lj_ir.c' l='350' u='m' c='lj_ir_knull'/>
<use f='luajit/lj_ir.c' l='373' u='m' c='lj_ir_kslot'/>
<use f='luajit/lj_ir.c' l='389' u='m' c='lj_ir_kvalue'/>
<use f='luajit/lj_ir.c' l='391' u='m' c='lj_ir_kvalue'/>
<use f='luajit/lj_opt_dce.c' l='31' u='m' c='dce_marksnap'/>
<use f='luajit/lj_opt_dce.c' l='45' u='m' c='dce_propagate'/>
<use f='luajit/lj_opt_dce.c' l='46' u='m' c='dce_propagate'/>
<use f='luajit/lj_opt_dce.c' l='53' u='m' c='dce_propagate'/>
<use f='luajit/lj_opt_dce.c' l='54' u='m' c='dce_propagate'/>
<use f='luajit/lj_opt_fold.c' l='416' u='m' c='fold_kfold_int64arith2'/>
<use f='luajit/lj_opt_fold.c' l='157' u='m' c='fold_kfold_strref_snew'/>
<use f='luajit/lj_opt_fold.c' l='157' u='m' c='fold_kfold_strref_snew'/>
<use f='luajit/lj_opt_fold.c' l='609' u='m' c='fold_bufput_kgc'/>
<use f='luajit/lj_opt_fold.c' l='753' u='m' c='fold_kfold_add_kgc'/>
<use f='luajit/lj_opt_fold.c' l='861' u='m' c='fold_kfold_conv_knum_int_num'/>
<use f='luajit/lj_opt_fold.c' l='157' u='m' c='fold_shortcut_dropleft'/>
<use f='luajit/lj_opt_fold.c' l='157' u='m' c='fold_shortcut_leftleft'/>
<use f='luajit/lj_opt_fold.c' l='157' u='m' c='fold_simplify_numadd_negx'/>
<use f='luajit/lj_opt_fold.c' l='157' u='m' c='fold_simplify_numadd_xneg'/>
<use f='luajit/lj_opt_fold.c' l='157' u='m' c='fold_simplify_numsub_negk'/>
<use f='luajit/lj_opt_fold.c' l='157' u='m' c='fold_simplify_numsub_xneg'/>
<use f='luajit/lj_opt_fold.c' l='157' u='m' c='fold_simplify_nummuldiv_negk'/>
<use f='luajit/lj_opt_fold.c' l='157' u='m' c='fold_simplify_nummuldiv_negneg'/>
<use f='luajit/lj_opt_fold.c' l='157' u='m' c='fold_simplify_nummuldiv_negneg'/>
<use f='luajit/lj_opt_fold.c' l='1129' u='m' c='fold_simplify_numpow_kx'/>
<use f='luajit/lj_opt_fold.c' l='157' u='m' c='fold_shortcut_conv_num_int'/>
<use f='luajit/lj_opt_fold.c' l='1151' u='m' c='fold_shortcut_conv_num_int'/>
<use f='luajit/lj_opt_fold.c' l='157' u='m' c='fold_simplify_conv_i64_num'/>
<use f='luajit/lj_opt_fold.c' l='157' u='m' c='fold_simplify_conv_int_i64'/>
<use f='luajit/lj_opt_fold.c' l='157' u='m' c='fold_simplify_conv_flt_num'/>
<use f='luajit/lj_opt_fold.c' l='157' u='m' c='fold_simplify_conv_sext'/>
<use f='luajit/lj_opt_fold.c' l='1260' u='m' c='fold_simplify_conv_sext'/>
<use f='luajit/lj_opt_fold.c' l='1260' u='m' c='fold_simplify_conv_sext'/>
<use f='luajit/lj_opt_fold.c' l='1301' u='m' c='fold_simplify_conv_narrow'/>
<use f='luajit/lj_opt_fold.c' l='157' u='m' c='fold_simplify_conv_narrow'/>
<use f='luajit/lj_opt_fold.c' l='1318' u='m' c='fold_cse_conv'/>
<use f='luajit/lj_opt_fold.c' l='1324' u='m' c='fold_cse_conv'/>
<use f='luajit/lj_opt_fold.c' l='157' u='m' c='fold_narrow_convert'/>
<use f='luajit/lj_opt_fold.c' l='1481' u='m' c='fold_simplify_intsub'/>
<use f='luajit/lj_opt_fold.c' l='1482' u='m' c='fold_simplify_intsub'/>
<use f='luajit/lj_opt_fold.c' l='1489' u='m' c='fold_simplify_intsubadd_leftcancel'/>
<use f='luajit/lj_opt_fold.c' l='157' u='m' c='fold_simplify_intsubadd_leftcancel'/>
<use f='luajit/lj_opt_fold.c' l='1502' u='m' c='fold_simplify_intsubsub_leftcancel'/>
<use f='luajit/lj_opt_fold.c' l='157' u='m' c='fold_simplify_intsubsub_leftcancel'/>
<use f='luajit/lj_opt_fold.c' l='1516' u='m' c='fold_simplify_intsubsub_rightcancel'/>
<use f='luajit/lj_opt_fold.c' l='157' u='m' c='fold_simplify_intsubsub_rightcancel'/>
<use f='luajit/lj_opt_fold.c' l='1527' u='m' c='fold_simplify_intsubadd_rightcancel'/>
<use f='luajit/lj_opt_fold.c' l='157' u='m' c='fold_simplify_intsubadd_rightcancel'/>
<use f='luajit/lj_opt_fold.c' l='1546' u='m' c='fold_simplify_intsubaddadd_cancel'/>
<use f='luajit/lj_opt_fold.c' l='157' u='m' c='fold_simplify_intsubaddadd_cancel'/>
<use f='luajit/lj_opt_fold.c' l='157' u='m' c='fold_simplify_intsubaddadd_cancel'/>
<use f='luajit/lj_opt_fold.c' l='1622' u='m' c='fold_simplify_shift_ik'/>
<use f='luajit/lj_opt_fold.c' l='157' u='m' c='fold_simplify_shift_andk'/>
<use f='luajit/lj_opt_fold.c' l='1656' u='m' c='fold_simplify_shift_andk'/>
<use f='luajit/lj_opt_fold.c' l='157' u='m' c='fold_simplify_shiftk_andk'/>
<use f='luajit/lj_opt_fold.c' l='157' u='m' c='fold_simplify_andor_k'/>
<use f='luajit/lj_opt_fold.c' l='157' u='m' c='fold_simplify_andor_k64'/>
<use f='luajit/lj_opt_fold.c' l='157' u='m' c='fold_reassoc_intarith_k'/>
<use f='luajit/lj_opt_fold.c' l='157' u='m' c='fold_reassoc_intarith_k64'/>
<use f='luajit/lj_opt_fold.c' l='157' u='m' c='fold_reassoc_bxor'/>
<use f='luajit/lj_opt_fold.c' l='157' u='m' c='fold_reassoc_shift'/>
<use f='luajit/lj_opt_fold.c' l='1858' u='m' c='fold_reassoc_shift'/>
<use f='luajit/lj_opt_fold.c' l='157' u='m' c='fold_reassoc_minmax_k'/>
<use f='luajit/lj_opt_fold.c' l='1952' u='m' c='fold_abc_invar'/>
<use f='luajit/lj_opt_fold.c' l='1953' u='m' c='fold_abc_invar'/>
<use f='luajit/lj_opt_fold.c' l='1988' u='m' c='fold_comm_equal'/>
<use f='luajit/lj_opt_fold.c' l='2004' u='m' c='fold_comm_comp'/>
<use f='luajit/lj_opt_fold.c' l='2038' u='m' c='fold_comm_bxor'/>
<use f='luajit/lj_opt_fold.c' l='2047' u='m' c='kfold_xload'/>
<use f='luajit/lj_opt_fold.c' l='157' u='m' c='fold_merge_eqne_snew_kgc'/>
<use f='luajit/lj_opt_fold.c' l='157' u='m' c='fold_fload_str_len_snew'/>
<use f='luajit/lj_opt_fold.c' l='2295' u='m' c='fold_fload_cdata_int64_kgc'/>
<use f='luajit/lj_opt_fold.c' l='2517' u='m' c='lj_opt_fold'/>
<use f='luajit/lj_opt_fold.c' l='2543' u='m' c='lj_opt_cse'/>
<use f='luajit/lj_opt_fold.c' l='2555' u='m' c='lj_opt_cse'/>
<use f='luajit/lj_opt_fold.c' l='2556' u='w' c='lj_opt_cse'/>
<use f='luajit/lj_opt_fold.c' l='2556' u='r' c='lj_opt_cse'/>
<use f='luajit/lj_opt_loop.c' l='115' u='m' c='loop_emit_phi'/>
<use f='luajit/lj_opt_loop.c' l='120' u='m' c='loop_emit_phi'/>
<use f='luajit/lj_opt_loop.c' l='131' u='m' c='loop_emit_phi'/>
<use f='luajit/lj_opt_loop.c' l='133' u='m' c='loop_emit_phi'/>
<use f='luajit/lj_opt_loop.c' l='138' u='m' c='loop_emit_phi'/>
<use f='luajit/lj_opt_loop.c' l='141' u='m' c='loop_emit_phi'/>
<use f='luajit/lj_opt_loop.c' l='152' u='m' c='loop_emit_phi'/>
<use f='luajit/lj_opt_loop.c' l='162' u='m' c='loop_emit_phi'/>
<use f='luajit/lj_opt_loop.c' l='163' u='m' c='loop_emit_phi'/>
<use f='luajit/lj_opt_loop.c' l='163' u='m' c='loop_emit_phi'/>
<use f='luajit/lj_opt_loop.c' l='165' u='m' c='loop_emit_phi'/>
<use f='luajit/lj_opt_loop.c' l='180' u='m' c='loop_emit_phi'/>
<use f='luajit/lj_opt_loop.c' l='182' u='m' c='loop_emit_phi'/>
<use f='luajit/lj_opt_loop.c' l='183' u='m' c='loop_emit_phi'/>
<use f='luajit/lj_opt_loop.c' l='193' u='m' c='loop_emit_phi'/>
<use f='luajit/lj_opt_loop.c' l='196' u='m' c='loop_emit_phi'/>
<use f='luajit/lj_opt_loop.c' l='197' u='m' c='loop_emit_phi'/>
<use f='luajit/lj_opt_loop.c' l='199' u='m' c='loop_emit_phi'/>
<use f='luajit/lj_opt_loop.c' l='200' u='m' c='loop_emit_phi'/>
<use f='luajit/lj_opt_loop.c' l='329' u='r' c='loop_unroll'/>
<use f='luajit/lj_opt_loop.c' l='336' u='m' c='loop_unroll'/>
<use f='luajit/lj_opt_loop.c' l='336' u='m' c='loop_unroll'/>
<use f='luajit/lj_opt_loop.c' l='337' u='m' c='loop_unroll'/>
<use f='luajit/lj_opt_loop.c' l='343' u='m' c='loop_unroll'/>
<use f='luajit/lj_opt_loop.c' l='344' u='m' c='loop_unroll'/>
<use f='luajit/lj_opt_loop.c' l='346' u='m' c='loop_unroll'/>
<use f='luajit/lj_opt_loop.c' l='348' u='m' c='loop_unroll'/>
<use f='luajit/lj_opt_loop.c' l='365' u='m' c='loop_unroll'/>
<use f='luajit/lj_opt_loop.c' l='366' u='m' c='loop_unroll'/>
<use f='luajit/lj_opt_loop.c' l='401' u='m' c='loop_undo'/>
<use f='luajit/lj_opt_loop.c' l='402' u='m' c='loop_undo'/>
<use f='luajit/lj_opt_mem.c' l='124' u='m' c='aa_ahref'/>
<use f='luajit/lj_opt_mem.c' l='124' u='m' c='aa_ahref'/>
<use f='luajit/lj_opt_mem.c' l='166' u='m' c='fwd_ahload'/>
<use f='luajit/lj_opt_mem.c' l='185' u='m' c='fwd_ahload'/>
<use f='luajit/lj_opt_mem.c' l='187' u='m' c='fwd_ahload'/>
<use f='luajit/lj_opt_mem.c' l='188' u='m' c='fwd_ahload'/>
<use f='luajit/lj_opt_mem.c' l='188' u='m' c='fwd_ahload'/>
<use f='luajit/lj_opt_mem.c' l='189' u='m' c='fwd_ahload'/>
<use f='luajit/lj_opt_mem.c' l='189' u='m' c='fwd_ahload'/>
<use f='luajit/lj_opt_mem.c' l='190' u='m' c='fwd_ahload'/>
<use f='luajit/lj_opt_mem.c' l='199' u='m' c='fwd_ahload'/>
<use f='luajit/lj_opt_mem.c' l='201' u='m' c='fwd_ahload'/>
<use f='luajit/lj_opt_mem.c' l='283' u='m' c='lj_opt_fwd_hrefk'/>
<use f='luajit/lj_opt_mem.c' l='295' u='m' c='lj_opt_fwd_href_nokey'/>
<use f='luajit/lj_opt_mem.c' l='369' u='m' c='lj_opt_dse_ahstore'/>
<use f='luajit/lj_opt_mem.c' l='397' u='r' c='lj_opt_fwd_alen'/>
<use f='luajit/lj_opt_mem.c' l='397' u='r' c='lj_opt_fwd_alen'/>
<use f='luajit/lj_opt_mem.c' l='424' u='m' c='lj_opt_fwd_alen'/>
<use f='luajit/lj_opt_mem.c' l='530' u='m' c='lj_opt_dse_ustore'/>
<use f='luajit/lj_opt_mem.c' l='630' u='m' c='lj_opt_dse_fstore'/>
<use f='luajit/lj_opt_mem.c' l='680' u='m' c='aa_xref'/>
<use f='luajit/lj_opt_mem.c' l='680' u='m' c='aa_xref'/>
<use f='luajit/lj_opt_mem.c' l='705' u='m' c='aa_xref'/>
<use f='luajit/lj_opt_mem.c' l='705' u='m' c='aa_xref'/>
<use f='luajit/lj_opt_mem.c' l='707' u='m' c='aa_xref'/>
<use f='luajit/lj_opt_mem.c' l='707' u='m' c='aa_xref'/>
<use f='luajit/lj_opt_mem.c' l='707' u='m' c='aa_xref'/>
<use f='luajit/lj_opt_mem.c' l='707' u='m' c='aa_xref'/>
<use f='luajit/lj_opt_mem.c' l='715' u='m' c='aa_xref'/>
<use f='luajit/lj_opt_mem.c' l='715' u='m' c='aa_xref'/>
<use f='luajit/lj_opt_mem.c' l='716' u='m' c='aa_xref'/>
<use f='luajit/lj_opt_mem.c' l='717' u='m' c='aa_xref'/>
<use f='luajit/lj_opt_mem.c' l='717' u='m' c='aa_xref'/>
<use f='luajit/lj_opt_mem.c' l='762' u='m' c='reassoc_xref'/>
<use f='luajit/lj_opt_mem.c' l='809' u='m' c='lj_opt_fwd_xload'/>
<use f='luajit/lj_opt_mem.c' l='809' u='m' c='lj_opt_fwd_xload'/>
<use f='luajit/lj_opt_mem.c' l='810' u='m' c='lj_opt_fwd_xload'/>
<use f='luajit/lj_opt_mem.c' l='810' u='m' c='lj_opt_fwd_xload'/>
<use f='luajit/lj_opt_mem.c' l='833' u='m' c='lj_opt_fwd_xload'/>
<use f='luajit/lj_opt_mem.c' l='833' u='m' c='lj_opt_fwd_xload'/>
<use f='luajit/lj_opt_mem.c' l='881' u='m' c='lj_opt_dse_xstore'/>
<use f='luajit/lj_opt_mem.c' l='917' u='m' c='lj_opt_fwd_wasnonnil'/>
<use f='luajit/lj_opt_mem.c' l='918' u='m' c='lj_opt_fwd_wasnonnil'/>
<use f='luajit/lj_opt_mem.c' l='922' u='m' c='lj_opt_fwd_wasnonnil'/>
<use f='luajit/lj_opt_mem.c' l='922' u='m' c='lj_opt_fwd_wasnonnil'/>
<use f='luajit/lj_opt_mem.c' l='937' u='m' c='lj_opt_fwd_wasnonnil'/>
<use f='luajit/lj_opt_narrow.c' l='311' u='m' c='narrow_conv_backprop'/>
<use f='luajit/lj_opt_narrow.c' l='311' u='m' c='narrow_conv_backprop'/>
<use f='luajit/lj_opt_narrow.c' l='361' u='m' c='narrow_conv_emit'/>
<use f='luajit/lj_opt_narrow.c' l='413' u='m' c='lj_opt_narrow_convert'/>
<use f='luajit/lj_opt_narrow.c' l='436' u='m' c='narrow_stripov'/>
<use f='luajit/lj_opt_narrow.c' l='445' u='m' c='narrow_stripov'/>
<use f='luajit/lj_opt_sink.c' l='42' u='m' c='sink_phidep'/>
<use f='luajit/lj_opt_sink.c' l='53' u='m' c='sink_checkphi'/>
<use f='luajit/lj_opt_sink.c' l='54' u='m' c='sink_checkphi'/>
<use f='luajit/lj_opt_sink.c' l='82' u='m' c='sink_mark_ins'/>
<use f='luajit/lj_opt_sink.c' l='85' u='m' c='sink_mark_ins'/>
<use f='luajit/lj_opt_sink.c' l='86' u='m' c='sink_mark_ins'/>
<use f='luajit/lj_opt_sink.c' l='90' u='m' c='sink_mark_ins'/>
<use f='luajit/lj_opt_sink.c' l='91' u='m' c='sink_mark_ins'/>
<use f='luajit/lj_opt_sink.c' l='92' u='m' c='sink_mark_ins'/>
<use f='luajit/lj_opt_sink.c' l='97' u='m' c='sink_mark_ins'/>
<use f='luajit/lj_opt_sink.c' l='101' u='m' c='sink_mark_ins'/>
<use f='luajit/lj_opt_sink.c' l='105' u='m' c='sink_mark_ins'/>
<use f='luajit/lj_opt_sink.c' l='111' u='m' c='sink_mark_ins'/>
<use f='luajit/lj_opt_sink.c' l='120' u='m' c='sink_mark_ins'/>
<use f='luajit/lj_opt_sink.c' l='121' u='m' c='sink_mark_ins'/>
<use f='luajit/lj_opt_sink.c' l='125' u='m' c='sink_mark_ins'/>
<use f='luajit/lj_opt_sink.c' l='125' u='m' c='sink_mark_ins'/>
<use f='luajit/lj_opt_sink.c' l='126' u='m' c='sink_mark_ins'/>
<use f='luajit/lj_opt_sink.c' l='127' u='m' c='sink_mark_ins'/>
<use f='luajit/lj_opt_sink.c' l='142' u='m' c='sink_mark_snap'/>
<use f='luajit/lj_opt_sink.c' l='155' u='m' c='sink_remark_phi'/>
<use f='luajit/lj_opt_sink.c' l='155' u='m' c='sink_remark_phi'/>
<use f='luajit/lj_opt_sink.c' l='157' u='m' c='sink_remark_phi'/>
<use f='luajit/lj_opt_sink.c' l='157' u='m' c='sink_remark_phi'/>
<use f='luajit/lj_opt_sink.c' l='158' u='m' c='sink_remark_phi'/>
<use f='luajit/lj_opt_sink.c' l='159' u='m' c='sink_remark_phi'/>
<use f='luajit/lj_opt_sink.c' l='172' u='m' c='sink_sweep_ins'/>
<use f='luajit/lj_opt_sink.c' l='181' u='m' c='sink_sweep_ins'/>
<use f='luajit/lj_opt_sink.c' l='184' u='m' c='sink_sweep_ins'/>
<use f='luajit/lj_opt_sink.c' l='192' u='m' c='sink_sweep_ins'/>
<use f='luajit/lj_opt_sink.c' l='193' u='m' c='sink_sweep_ins'/>
<use f='luajit/lj_opt_sink.c' l='197' u='m' c='sink_sweep_ins'/>
<use f='luajit/lj_opt_sink.c' l='203' u='m' c='sink_sweep_ins'/>
<use f='luajit/lj_opt_sink.c' l='213' u='m' c='sink_sweep_ins'/>
<use f='luajit/lj_opt_sink.c' l='219' u='m' c='sink_sweep_ins'/>
<use f='luajit/lj_opt_sink.c' l='222' u='m' c='sink_sweep_ins'/>
<use f='luajit/lj_record.c' l='2609' u='m' c='lj_record_setup'/>
<use f='luajit/lj_snap.c' l='101' u='m' c='snapshot_slots'/>
<use f='luajit/lj_snap.c' l='416' u='m' c='snap_replay_const'/>
<use f='luajit/lj_snap.c' l='416' u='m' c='snap_replay_const'/>
<use f='luajit/lj_snap.c' l='418' u='m' c='snap_replay_const'/>
<use f='luajit/lj_snap.c' l='447' u='m' c='snap_pref'/>
<use f='luajit/lj_snap.c' l='503' u='m' c='lj_snap_replay'/>
<use f='luajit/lj_snap.c' l='605' u='m' c='lj_snap_replay'/>
<use f='luajit/lj_snap.c' l='646' u='r' c='snap_restoreval'/>
<use f='luajit/lj_snap.c' l='733' u='m' c='snap_restoredata'/>
<use f='luajit/lj_snap.c' l='811' u='m' c='snap_unsink'/>
<use f='luajit/lj_snap.c' l='812' u='m' c='snap_unsink'/>
<use f='luajit/lj_snap.c' l='812' u='m' c='snap_unsink'/>
<use f='luajit/lj_snap.c' l='813' u='m' c='snap_unsink'/>
<use f='luajit/lj_snap.c' l='813' u='m' c='snap_unsink'/>
