<dec f='luajit/lj_lex.h' l='59' type='LexChar'/>
<offset>384</offset>
<doc f='luajit/lj_lex.h' l='59'>/* Current character. */</doc>
<use f='luajit/lj_bcread.c' l='51' u='r' c='bcread_fill'/>
<use f='luajit/lj_bcread.c' l='73' u='w' c='bcread_fill'/>
<use f='luajit/lj_lex.c' l='65' u='w' c='lex_next'/>
<use f='luajit/lj_lex.c' l='77' u='r' c='lex_savenext'/>
<use f='luajit/lj_lex.c' l='84' u='r' c='lex_newline'/>
<use f='luajit/lj_lex.c' l='43' u='r' c='lex_newline'/>
<use f='luajit/lj_lex.c' l='43' u='r' c='lex_newline'/>
<use f='luajit/lj_lex.c' l='87' u='r' c='lex_newline'/>
<use f='luajit/lj_lex.c' l='100' u='r' c='lex_number'/>
<use f='luajit/lj_lex.c' l='102' u='r' c='lex_number'/>
<use f='luajit/lj_lex.c' l='102' u='r' c='lex_number'/>
<use f='luajit/lj_lex.c' l='103' u='r' c='lex_number'/>
<use f='luajit/lj_lex.c' l='103' u='r' c='lex_number'/>
<use f='luajit/lj_lex.c' l='104' u='r' c='lex_number'/>
<use f='luajit/lj_lex.c' l='143' u='r' c='lex_skipeq'/>
<use f='luajit/lj_lex.c' l='147' u='r' c='lex_skipeq'/>
<use f='luajit/lj_lex.c' l='43' u='r' c='lex_longstring'/>
<use f='luajit/lj_lex.c' l='43' u='r' c='lex_longstring'/>
<use f='luajit/lj_lex.c' l='157' u='r' c='lex_longstring'/>
<use f='luajit/lj_lex.c' l='188' u='r' c='lex_string'/>
<use f='luajit/lj_lex.c' l='190' u='r' c='lex_string'/>
<use f='luajit/lj_lex.c' l='191' u='r' c='lex_string'/>
<use f='luajit/lj_lex.c' l='211' u='r' c='lex_string'/>
<use f='luajit/lj_lex.c' l='212' u='r' c='lex_string'/>
<use f='luajit/lj_lex.c' l='216' u='r' c='lex_string'/>
<use f='luajit/lj_lex.c' l='217' u='r' c='lex_string'/>
<use f='luajit/lj_lex.c' l='226' u='r' c='lex_string'/>
<use f='luajit/lj_lex.c' l='227' u='r' c='lex_string'/>
<use f='luajit/lj_lex.c' l='228' u='r' c='lex_string'/>
<use f='luajit/lj_lex.c' l='250' u='r' c='lex_string'/>
<use f='luajit/lj_lex.c' l='43' u='r' c='lex_string'/>
<use f='luajit/lj_lex.c' l='43' u='r' c='lex_string'/>
<use f='luajit/lj_lex.c' l='261' u='r' c='lex_string'/>
<use f='luajit/lj_lex.c' l='263' u='r' c='lex_string'/>
<use f='luajit/lj_lex.c' l='295' u='r' c='lex_scan'/>
<use f='luajit/lj_lex.c' l='297' u='r' c='lex_scan'/>
<use f='luajit/lj_lex.c' l='304' u='r' c='lex_scan'/>
<use f='luajit/lj_lex.c' l='311' u='r' c='lex_scan'/>
<use f='luajit/lj_lex.c' l='324' u='r' c='lex_scan'/>
<use f='luajit/lj_lex.c' l='326' u='r' c='lex_scan'/>
<use f='luajit/lj_lex.c' l='43' u='r' c='lex_scan'/>
<use f='luajit/lj_lex.c' l='43' u='r' c='lex_scan'/>
<use f='luajit/lj_lex.c' l='336' u='r' c='lex_scan'/>
<use f='luajit/lj_lex.c' l='353' u='r' c='lex_scan'/>
<use f='luajit/lj_lex.c' l='356' u='r' c='lex_scan'/>
<use f='luajit/lj_lex.c' l='359' u='r' c='lex_scan'/>
<use f='luajit/lj_lex.c' l='362' u='r' c='lex_scan'/>
<use f='luajit/lj_lex.c' l='365' u='r' c='lex_scan'/>
<use f='luajit/lj_lex.c' l='373' u='r' c='lex_scan'/>
<use f='luajit/lj_lex.c' l='378' u='r' c='lex_scan'/>
<use f='luajit/lj_lex.c' l='387' u='r' c='lex_scan'/>
<use f='luajit/lj_lex.c' l='415' u='r' c='lj_lex_setup'/>
<use f='luajit/lj_lex.c' l='421' u='r' c='lj_lex_setup'/>
<use f='luajit/lj_lex.c' l='424' u='r' c='lj_lex_setup'/>
<use f='luajit/lj_lex.c' l='43' u='r' c='lj_lex_setup'/>
<use f='luajit/lj_lex.c' l='43' u='r' c='lj_lex_setup'/>
<use f='luajit/lj_lex.c' l='429' u='r' c='lj_lex_setup'/>
<use f='luajit/lj_lib.c' l='63' u='w' c='lib_read_lfunc'/>
