<dec f='luajit/lj_lex.h' l='53' type='struct FuncState *'/>
<offset>0</offset>
<doc f='luajit/lj_lex.h' l='53'>/* Current FuncState. Defined in lj_parse.c. */</doc>
<use f='luajit/lj_lex.c' l='402' u='w' c='lj_lex_setup'/>
<use f='luajit/lj_parse.c' l='244' u='r' c='lj_parse_keepstr'/>
<use f='luajit/lj_parse.c' l='257' u='r' c='lj_parse_keepcdata'/>
<use f='luajit/lj_parse.c' l='1049' u='r' c='var_new'/>
<use f='luajit/lj_parse.c' l='1075' u='r' c='var_add'/>
<use f='luajit/lj_parse.c' l='1089' u='r' c='var_remove'/>
<use f='luajit/lj_parse.c' l='1158' u='r' c='gola_new'/>
<use f='luajit/lj_parse.c' l='1183' u='r' c='gola_patch'/>
<use f='luajit/lj_parse.c' l='1193' u='r' c='gola_close'/>
<use f='luajit/lj_parse.c' l='1216' u='r' c='gola_resolve'/>
<use f='luajit/lj_parse.c' l='1218' u='r' c='gola_resolve'/>
<use f='luajit/lj_parse.c' l='1251' u='r' c='gola_fixup'/>
<use f='luajit/lj_parse.c' l='1265' u='r' c='gola_findlabel'/>
<use f='luajit/lj_parse.c' l='1570' u='r' c='fs_finish'/>
<use f='luajit/lj_parse.c' l='1610' u='w' c='fs_finish'/>
<use f='luajit/lj_parse.c' l='1619' u='r' c='fs_init'/>
<use f='luajit/lj_parse.c' l='1619' u='w' c='fs_init'/>
<use f='luajit/lj_parse.c' l='1687' u='r' c='expr_field'/>
<use f='luajit/lj_parse.c' l='1700' u='r' c='expr_bracket'/>
<use f='luajit/lj_parse.c' l='1721' u='r' c='expr_table'/>
<use f='luajit/lj_parse.c' l='1830' u='r' c='parse_params'/>
<use f='luajit/lj_parse.c' l='1861' u='r' c='parse_body'/>
<use f='luajit/lj_parse.c' l='1897' u='r' c='expr_list'/>
<use f='luajit/lj_parse.c' l='1907' u='r' c='parse_args'/>
<use f='luajit/lj_parse.c' l='1954' u='r' c='expr_primary'/>
<use f='luajit/lj_parse.c' l='1961' u='r' c='expr_primary'/>
<use f='luajit/lj_parse.c' l='1151' u='r' c='expr_primary'/>
<use f='luajit/lj_parse.c' l='2013' u='r' c='expr_simple'/>
<use f='luajit/lj_parse.c' l='2101' u='r' c='expr_unop'/>
<use f='luajit/lj_parse.c' l='2115' u='r' c='expr_binop'/>
<use f='luajit/lj_parse.c' l='2118' u='r' c='expr_binop'/>
<use f='luajit/lj_parse.c' l='2136' u='r' c='expr_next'/>
<use f='luajit/lj_parse.c' l='2145' u='r' c='expr_cond'/>
<use f='luajit/lj_parse.c' l='2160' u='r' c='assign_hazard'/>
<use f='luajit/lj_parse.c' l='2185' u='r' c='assign_adjust'/>
<use f='luajit/lj_parse.c' l='2202' u='r' c='assign_adjust'/>
<use f='luajit/lj_parse.c' l='2216' u='r' c='parse_assignment'/>
<use f='luajit/lj_parse.c' l='2224' u='r' c='parse_assignment'/>
<use f='luajit/lj_parse.c' l='2225' u='r' c='parse_assignment'/>
<use f='luajit/lj_parse.c' l='2232' u='r' c='parse_assignment'/>
<use f='luajit/lj_parse.c' l='2238' u='r' c='parse_assignment'/>
<use f='luajit/lj_parse.c' l='2239' u='r' c='parse_assignment'/>
<use f='luajit/lj_parse.c' l='2245' u='r' c='parse_call_assign'/>
<use f='luajit/lj_parse.c' l='2261' u='r' c='parse_local'/>
<use f='luajit/lj_parse.c' l='1151' u='r' c='parse_func'/>
<use f='luajit/lj_parse.c' l='2306' u='r' c='parse_func'/>
<use f='luajit/lj_parse.c' l='2328' u='r' c='parse_return'/>
<use f='luajit/lj_parse.c' l='2365' u='r' c='parse_break'/>
<use f='luajit/lj_parse.c' l='2366' u='r' c='parse_break'/>
<use f='luajit/lj_parse.c' l='2372' u='r' c='parse_goto'/>
<use f='luajit/lj_parse.c' l='2384' u='r' c='parse_label'/>
<use f='luajit/lj_parse.c' l='2418' u='r' c='parse_block'/>
<use f='luajit/lj_parse.c' l='2428' u='r' c='parse_while'/>
<use f='luajit/lj_parse.c' l='2448' u='r' c='parse_repeat'/>
<use f='luajit/lj_parse.c' l='2475' u='r' c='parse_for_num'/>
<use f='luajit/lj_parse.c' l='2545' u='r' c='parse_for_iter'/>
<use f='luajit/lj_parse.c' l='2587' u='r' c='parse_for'/>
<use f='luajit/lj_parse.c' l='2617' u='r' c='parse_if'/>
<use f='luajit/lj_parse.c' l='2709' u='r' c='parse_chunk'/>
<use f='luajit/lj_parse.c' l='2709' u='r' c='parse_chunk'/>
