<dec f='luajit/lauxlib.h' l='138' type='lua_State *'/>
<use f='luajit/lib_aux.c' l='188' u='r' c='emptybuffer'/>
<use f='luajit/lib_aux.c' l='197' u='r' c='adjuststack'/>
<use f='luajit/lib_aux.c' l='226' u='r' c='luaL_addlstring'/>
<use f='luajit/lib_aux.c' l='240' u='r' c='luaL_pushresult'/>
<use f='luajit/lib_aux.c' l='246' u='r' c='luaL_addvalue'/>
<use f='luajit/lib_aux.c' l='263' u='w' c='luaL_buffinit'/>
<offset>128</offset>
